### ISSUE TITLE
分隔符前后不能添加空格

### ISSUE THREAD

**Issue by Aqours** [tangshuang/wp-seo#1]
seo_clear_code 函数中有一段
```
$string = trim($string);
```
去掉了用户输入的空格，建议去掉这段代码。
否则，这样（name - description）的用法没法在分隔符前后添加空格。

**Comment by tangshuang** [comment]
这种情况可以在标题形式里面去配置，比如{blog_name} {split} {blog_description}，在具体的格式里面去规定格式的东西

**Comment by Aqours** [comment]
在文章中时，按你这样的方式使用，会出现 {article_title} - {blog_name}-{blog_description}，前一个分隔符有空格而后一个分隔符却没有空格的情况
